project:
  type: website
  output-dir: docs

website:
  title: "Alina Bolshakova"
  site-url: https://ayablck.github.io
  description: "Data and financial analyst — SQL, Python, machine learning."
  favicon: images/favicon-32x32.png
  navbar:
    logo: images/logo.png
    right: # accepts right/left/center; you can also place items individually on the left, right, and center
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects/index.qmd
        text: Projects
      - href: contact.qmd
        text: Contact
      - icon: github # add icons as navbar buttons
        href: https://github.com/AyaBlck
        target: _blank
  page-footer:
    background: light #or dark
    left: Copyright 2026, Alina Bolshakova
    right: This website is built with [GitHub](https://github.com/AyaBlck/AyaBlck.github.io){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme:
      dark: [darkly, styles-dark.scss]
      light: [cosmo, styles.scss]
    toc: true


